/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class contoursolveinterface_Contour */

#ifndef _Included_contoursolveinterface_Contour
#define _Included_contoursolveinterface_Contour
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     contoursolveinterface_Contour
 * Method:    create
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_contoursolveinterface_Contour_create
  (JNIEnv *, jobject);

/*
 * Class:     contoursolveinterface_Contour
 * Method:    addPoint
 * Signature: (IDIDI)I
 */
JNIEXPORT jint JNICALL Java_contoursolveinterface_Contour_addPoint
  (JNIEnv *, jobject, jint, jdouble, jint, jdouble, jint);

/*
 * Class:     contoursolveinterface_Contour
 * Method:    addLine
 * Signature: (IDIDIDIZ)I
 */
JNIEXPORT jint JNICALL Java_contoursolveinterface_Contour_addLine
  (JNIEnv *, jobject, jint, jdouble, jint, jdouble, jint, jdouble, jint, jboolean);

/*
 * Class:     contoursolveinterface_Contour
 * Method:    addArc
 * Signature: (IDIDIDIDIDIDIDIZ)I
 */
JNIEXPORT jint JNICALL Java_contoursolveinterface_Contour_addArc
  (JNIEnv *, jobject, jint, jdouble, jint, jdouble, jint, jdouble, jint, jdouble, jint, jdouble, jint, jdouble, jint, jdouble, jint, jboolean);

/*
 * Class:     contoursolveinterface_Contour
 * Method:    solve
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_contoursolveinterface_Contour_solve
  (JNIEnv *, jobject, jint);

/*
 * Class:     contoursolveinterface_Contour
 * Method:    getSolution
 * Signature: (II)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_contoursolveinterface_Contour_getSolution
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     contoursolveinterface_Contour
 * Method:    size
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_contoursolveinterface_Contour_size
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
